language: python
dist: bionic
python:
  - "3.6"
sudo: required
env:
  - TEST_POSTGRES=/usr/lib/postgresql/10/bin/postgres TEST_INITDB=/usr/lib/postgresql/10/bin/initdb
# command to install dependencies
install:
  - rm -rf /var/lib/postgresql
  - DEBIAN_FRONTEND=noninteractive apt-get install -qq postgresql-10 postgresql-contrib-10 postgis
  - pip install coveralls
  - "pip install --upgrade -r requirements.txt"
  - "pip install --upgrade -r optional-requirements.txt"
  - pip install -e .

# command to run tests
script:
  - coverage run --source=gengine gengine/app/tests/runner.py

after_success:
  coveralls

# deploy to pypi
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true

notifications:
  email:
    recipients:
      - $ADMIN_EMAIL
    on_success: always # default: change
    on_failure: always # default: always
